#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "160px"
logo_height = "32px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Satyam Jay"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "dark" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.


# search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true


# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Satyam Jay", "PHD at IIT"]
description = "Satyam Jay's website"
author = "Satyam Jay"
image = "images/og-image.png"


# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]
