######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "/"
# Title of your website (required).
title = "Satyam Jay"
# Your theme name
theme = "hugoplate"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Asia/Kolkata"
# post pagination
paginate = 2 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage


########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slugorfilename/"


############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[[module.imports]]
path = 'github.com/hugomods/images'

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]


########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"

# JS Plugins
[[params.plugins.js]]
link = "js/search.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
link = "js/gallery-slider.js"
[[params.plugins.js]]
link = "js/accordion.js"
[[params.plugins.js]]
link = "js/tab.js"
[[params.plugins.js]]
link = "js/modal.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/youtube-lite.js"

# [params]
#     author = "CowboySmall"
#     description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
#     primaryColor = "#54B689"
#     textPrimaryColor = "#292929"

#     [params.profile]
#         enable = true
#         name = "Simon Doe"
#         tagline = "Senior Software Engineer"
#         avatar = "avatar.png"

#     [params.contact]
#         enable = true
#         location = "New York"

#         [[params.contact.list]]
#         icon = "fas fa-phone-square"
#         url = "tel:#"
#         text = "0123 4567 890"
#         [[params.contact.list]]
#         icon = "fas fa-envelope-square"
#         url = "mailto:#"
#         text = "simon.doe@yourwebsite.com"
#         [[params.contact.list]]
#         icon = "fas fa-globe"
#         url = "#"
#         text = "www.yourwebsite.com"

#     [params.skills]
#         enable = true

#         [[params.skills.list]]
#         title = "Technical"
#         [[params.skills.list.items]]
#         details = "JavaScript/Angular/React/Vue"
#         [[params.skills.list.items]]
#         details = "Python/Ruby/PHP"
#         [[params.skills.list.items]]
#         details = "Node.js/ASP.NET"
#         [[params.skills.list.items]]
#         details = "PostgreSQL/MySQL"
#         [[params.skills.list.items]]
#         details = "Object-oriented design"
#         [[params.skills.list.items]]
#         details = "Design and implement database structures"
#         [[params.skills.list.items]]
#         details = "Lead and deliver complex software systems"

#         [[params.skills.list]]
#         title = "Professional"
#         [[params.skills.list.items]]
#         details = "Effective communication"
#         [[params.skills.list.items]]
#         details = "Team player"
#         [[params.skills.list.items]]
#         details = "Strong problem solver"
#         [[params.skills.list.items]]
#         details = "Good time management"

#     [params.education]
#         enable = true

#         [[params.education.list]]
#         degree = "MSc in Computer Science"
#         university = "University College London"
#         dates = "2010 - 2011"
#         [[params.education.list]]
#         degree = "BSc Maths and Physics"
#         university = "Imperial College London"
#         dates = "2007 - 2010"


#     [params.awards]
#         enable = true

#         [[params.awards.list]]
#         name = "Award Lorem Ipsum"
#         body = "Microsoft lorem ipsum"
#         date = "2019"
#         [[params.awards.list]]
#         name = "Award Donec Sodales"
#         body = "Oracle Aenean"
#         date = "2017"

#     [params.languages]
#         enable = true

#         [[params.languages.list]]
#         name = "English"
#         level = "Native"
#         [[params.languages.list]]
#         name = "Spanish"
#         level = "Professional"


#     [params.interests]
#         enable = true

#         [[params.interests.list]]
#         name = "Climbing"
#         [[params.interests.list]]
#         name = "Snowboarding"
#         [[params.interests.list]]
#         name = "Photography"
#         [[params.interests.list]]
#         name = "Travelling"


#     [params.summary]
#         enable = true
#         text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."


#     [params.experience]
#         enable = true

#         [[params.experience.list]]
#         title = "Senior Software Engineer"
#         dates = "2019 - Present"
#         company = "Google"
#         details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
#         [[params.experience.list.items]]
#         details = "Lorem ipsum dolor sit amet, consectetuer."
#         [[params.experience.list.items]]
#         details = "Aenean commodo ligula eget dolor."
#         [[params.experience.list.items]]
#         details = "Etiam ultricies nisi vel augue."

#         [[params.experience.list]]
#         title = "Lead Software Developer"
#         dates = "2016 - 2019"
#         company = "Apple"
#         details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
#         [[params.experience.list.items]]
#         details = "Lorem ipsum dolor sit amet, consectetuer."
#         [[params.experience.list.items]]
#         details = "Aenean commodo ligula eget dolor."

#         [[params.experience.list]]
#         title = "Senior Software Developer"
#         dates = "2014 - 2016"
#         company = "Dropbox"
#         details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

#         [[params.experience.list]]
#         title = "Senior Developer"
#         dates = "2013 - 2014"
#         company = "Uber"
#         details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

#         [[params.experience.list]]
#         title = "Backend Developer"
#         dates = "2014 - 2016"
#         company = "Amazon"
#         details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

#         [[params.experience.list]]
#         title = "Frontend Developer"
#         dates = "2013 - 2014"
#         company = "Startup"
#         details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."


#     [params.projects]
#         enable = true

#         [[params.projects.list]]
#         title = "Project Lorem Ipsum"
#         meta = "Open Source"
#         tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

#         [[params.projects.list]]
#         title = "Project Sed Fringilla"
#         meta = "Open Source"
#         tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

#         [[params.projects.list]]
#         title = "Project Praesent"
#         meta = "Open Source"
#         tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


#     [params.information]
#         enable = true

#         [[params.information.list]]
#         title = "Papers"
#         [[params.information.list.items]]
#         details = "2018 · Lorem Ipsum"
#         [[params.information.list.items]]
#         details = "2016 · Sed Fringilla"

#         [[params.information.list]]
#         title = "Interests"
#         details = "Climbing, Snowboarding, Photography, Travelling"

#     [params.social]
#         enable = true

#         [[params.social.list]]
#         icon = "fab fa-github-square"
#         url = "//github.com/username"
#         title = "username"
#         [[params.social.list]]
#         icon = "fab fa-linkedin"
#         url = "//linkedin.com/in/username"
#         title = "username"
#         [[params.social.list]]
#         icon = "fab fa-twitter-square"
#         url = "//twitter.com/username"
#         title = "@username"
