site_name: Satyam Jay
site_url: https://satyamjay-iitd.github.io/
site_description: Satyam's website

theme:
  name: material
  icon:
    logo: fontawesome/solid/computer
    annotation: material/arrow-right-circle
  favicon: assets/favicon.png
  font:
    text: Roboto

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate 
    - content.code.copy

  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - social
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date.created
      categories:
        - categories
        - tags 

  - blog:
      blog_toc: true
      post_excerpt: required
      categories_allowed:
        - system
        - streaming
        - latency
        - article
        - list
        - paper
        - dev-diary


markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/satyamjay-iitd
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/satyam-jay-72858412b
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml
      name: "Subscribe to RSS Feed"

